major refactor of shell scripts, magit commit perf fix, other changes from KD21QWDKW7

diff --git a/home/scripts/docker-shell b/home/scripts/docker-shell
--- a/home/scripts/docker-shell
+++ b/home/scripts/docker-shell
@@ -1,16 +1,41 @@
 #!/usr/bin/env zsh
 
-local image="${1:-$(pcregrep -o 'volterra.*go-builder:v?[\d\.]+' .gitlab-ci.yml)}" 
-if [[ -z "$image" ]]
-then
-	echo "ERROR: no image specified, and go-builder image could not be derived from .gitlab-ci.yml" >&2
+set -Eeuo pipefail
+group_id=${GID:-$(id -g)}
+user_id=${UID:-$(id -u)}
+
+image="${1:-$(pcregrep -o 'volterra.*go-builder:v?[\d\.]+' .gitlab-ci.yml)}"
+if [[ -z "$image" ]]; then
+  echo "ERROR: no image specified, and go-builder image could not be derived from .gitlab-ci.yml" >&2
+  exit 1
 else
-	local cmd="${2:-bash}" 
-	local temp_passwd_file="$(mktemp)" 
-	local project_root="$(git rev-parse --show-toplevel)" 
-	local go_src_dir=$(echo $project_root | sed "s^.*src/\(.*\)^src/\1^") 
-	local go_cache_dir="${project_root}/.cache-docker/go" 
-	echo "running container shell with $image"
-	echo "${USER}:x:${UID}:${GID}:Volterra User:${HOME}:/bin/bash" > "$temp_passwd_file" && mkdir -p "${project_root}/.cache.go" && docker run --rm -it --user ${UID}:${GID} --userns=host --env GOCACHE=${go_cache_dir} --env GOPATH=${GOPATH} --env HOME=${HOME} --env DOCKER_IMAGE="$image" --net host -v ${HOME}/.ssh/known_hosts:${HOME}/.ssh/known_hosts:ro,Z -v ${HOME}/.cache:${HOME}/.cache -v "$temp_passwd_file":/etc/passwd:ro,Z -v ${PWD}:/go/${GOPATH}/src:Z -v ${HOME}/.gitconfig:${HOME}/.gitconfig:ro -v ${HOME}/.ssh:${HOME}/.ssh:ro -v ${HOME}/.magefile:${HOME}/.magefile -v ${GOPATH}:${GOPATH} -v ${project_root}:${project_root} -v "${HOME}/.bashrc-docker-shell":"${HOME}/.bashrc" -w ${project_root} ${image} ${cmd}
-	test -f "$temp_passwd_file" && rm -f "$temp_passwd_file"
+  cmd="${2:-bash}"
+  temp_passwd_file="$(mktemp)"
+  project_root="$(git rev-parse --show-toplevel)"
+  go_src_dir=$(echo $project_root | sed "s^.*src/\(.*\)^src/\1^")
+  go_cache_dir="${project_root}/.cache-docker/go"
+  echo "running container shell with $image"
+  echo "${USER}:x:${user_id}:${group_id}:Volterra User:${HOME}:/bin/bash" >"$temp_passwd_file" &&
+    mkdir -p "${project_root}/.cache.go" &&
+    docker run --rm -it \
+      --user ${user_id}:${group_id} \
+      --userns=host \
+      --env GOCACHE=${go_cache_dir} \
+      --env GOPATH=${GOPATH} \
+      --env HOME=${HOME} \
+      --env DOCKER_IMAGE="$image" \
+      --net host -v ${HOME}/.ssh/known_hosts:${HOME}/.ssh/known_hosts:ro,Z \
+      -v ${HOME}/.cache:${HOME}/.cache \
+      -v "$temp_passwd_file":/etc/passwd:ro,Z \
+      -v ${PWD}:/go/${GOPATH}/src:Z \
+      -v ${HOME}/.gitconfig:${HOME}/.gitconfig:ro \
+      -v ${HOME}/.ssh:${HOME}/.ssh:ro \
+      -v ${HOME}/.magefile:${HOME}/.magefile \
+      -v ${GOPATH}:${GOPATH} \
+      -v ${project_root}:${project_root} \
+      -v "${HOME}/.bashrc-docker-shell":"${HOME}/.bashrc" \
+      -w ${project_root} \
+      ${image} \
+      ${cmd}
+  test -f "$temp_passwd_file" && rm -f "$temp_passwd_file"
 fi
diff --git a/home/scripts/find-image-data b/home/scripts/find-image-data
--- a/home/scripts/find-image-data
+++ b/home/scripts/find-image-data
@@ -1,41 +1,39 @@
 #!/usr/bin/env zsh
 
-check-required-tools $0 skopeo jq || return 1
-if [[ $# -lt 1 ]]
-then
+set -Eeuo pipefail
+check-required-tools $0 skopeo jq || exit 1
+if [[ $# -lt 1 ]]; then
 	echo "usage: find-image-data [image-url|app-name commit-sha]" >&2
-	return 1
+	exit 1
 fi
-local app_name='' 
-local commit_sha='' 
-local image_data='' 
-if [[ $# == 1 ]]
-then
-	image_url="$1" 
-	image_data="$(skopeo inspect docker://${image_url} 2>/dev/null) | jq -r" 
-	if [[ $? -ne 0 ]]
-	then
+app_name=''
+commit_sha=''
+image_data=''
+if [[ $# == 1 ]]; then
+	image_url="$1"
+	image_data="$(skopeo inspect docker://${image_url} 2>/dev/null | jq -r)"
+	if [[ $? -ne 0 ]]; then
 		echo "error: unable to find image for ${image_url}" >&2
-		return 1
+		exit 1
 	fi
 else
-	app_name="$1" 
-	commit_sha="$2" 
-	image_data="$(skopeo inspect docker://gcr.io/volterraio/${app_name}:${commit_sha} 2>/dev/null) | jq -r" 
-	if [[ $? -ne 0 ]]
-	then
-		image_data="$(skopeo inspect docker://volterra.azurecr.io/ves.io/${app_name}:${commit_sha})" 
-		if [[ $? -ne 0 ]]
-		then
+	app_name="$1"
+	commit_sha="$2"
+	if ! image_data=$(skopeo inspect docker://gcr.io/volterraio/${app_name}:${commit_sha} 2>/dev/null); then
+		image_data="$(skopeo inspect docker://volterra.azurecr.io/ves.io/${app_name}:${commit_sha})"
+		if [[ $? -ne 0 ]]; then
 			acr-login
-			image_data="$(skopeo inspect docker://volterra.azurecr.io/ves.io/${app_name}:${commit_sha} 2>/dev/null) | jq -r" 
-			if [[ $? -ne 0 ]]
-			then
+			image_data="$(skopeo inspect docker://volterra.azurecr.io/ves.io/${app_name}:${commit_sha} 2>/dev/null | jq -r)"
+			if [[ $? -ne 0 ]]; then
 				echo "error: unable to find image for ${app_name}:${commit_sha}" >&2
 				echo "perhaps the pipeline failed or hasn't published an image yet, or perhaps the commit is gone from the origin?" >&2
-				return 1
+				exit 1
 			fi
 		fi
 	fi
+fi
+if [[ -z "$image_data" ]]; then
+	echo "error: no image data found for ${app_name}:${commit_sha}" >&2
+	exit 1
 fi
 echo "$image_data"
diff --git a/home/scripts/gitlab-test-failures b/home/scripts/gitlab-test-failures
--- a/home/scripts/gitlab-test-failures
+++ b/home/scripts/gitlab-test-failures
@@ -1,56 +1,49 @@
 #!/usr/bin/env zsh
 
-local project_id=${PROJECT_ID:-5509942} 
-local job_name=${JOB} 
-if [[ -z "$job_name" ]]
-then
+set -Eeuo pipefail
+
+project_id=${PROJECT_ID:-5509942}
+job_name=${JOB}
+if [[ -z "$job_name" ]]; then
 	echo "error: JOB is required" >&2
-	return 1
+	exit 1
 fi
-local test_name=${TEST_NAME} 
-if [[ -z "$test_name" ]]
-then
+test_name=${TEST_NAME}
+if [[ -z "$test_name" ]]; then
 	echo "error: TEST_NAME is required" >&2
-	return 1
+	exit 1
 fi
-local per_page=${PER_PAGE:-100} 
-local pages=${PAGES:-10} 
-local max_results=${MAX_RESULTS:-1} 
-local found_results=0 
-local curl_metadata_out_file=$(mktemp) 
-export IFS=$'\n' 
-while true
-do
-	results=$(curl -Ssv --globoff --header "PRIVATE-TOKEN: ${GITLAB_API_TOKEN}" "https://gitlab.com/api/v4/projects/${PROJECT_ID}/jobs?scope[]=failed&per_page=${PER_PAGE}&page=${page}" 2>$curl_metadata_out_file) 
-	if [[ $? -ne 0 ]]
-	then
+per_page=${PER_PAGE:-100}
+pages=${PAGES:-10}
+max_results=${MAX_RESULTS:-1}
+found_results=0
+curl_metadata_out_file=$(mktemp)
+export IFS=$'\n'
+while true; do
+	results=$(curl -Ssv --globoff --header "PRIVATE-TOKEN: ${GITLAB_API_TOKEN}" "https://gitlab.com/api/v4/projects/${PROJECT_ID}/jobs?scope[]=failed&per_page=${PER_PAGE}&page=${page}" 2>$curl_metadata_out_file)
+	if [[ $? -ne 0 ]]; then
 		echo "failed to get jobs" 2>&1
 		rm -f $curl_metadata_out_file
-		return 1
+		exit 1
 	fi
-	failed_job_ids=($(printf '%s\n' "$results" | jq 'map(select(.name=="unittest-client"))[]|.id')) 
-	for job_id in $failed_job_ids
-	do
-		job_log=$(curl -Ss --location --header "PRIVATE-TOKEN: ${GITLAB_API_TOKEN}" "https://gitlab.com/api/v4/projects/${PROJECT_ID}/jobs/${job_id}/trace") 
-		failed_tests=($(printf '%s\n' "$job_log" | pcregrep -o 'FAIL:\s*Test[\w_]+' | sd '^.*(Test.*)' '$1' | sort -u)) 
+	failed_job_ids=($(printf '%s\n' "$results" | jq 'map(select(.name=="unittest-client"))[]|.id'))
+	for job_id in $failed_job_ids; do
+		job_log=$(curl -Ss --location --header "PRIVATE-TOKEN: ${GITLAB_API_TOKEN}" "https://gitlab.com/api/v4/projects/${PROJECT_ID}/jobs/${job_id}/trace")
+		failed_tests=($(printf '%s\n' "$job_log" | pcregrep -o 'FAIL:\s*Test[\w_]+' | sd '^.*(Test.*)' '$1' | sort -u))
 		echo "\njob ID: $job_id found failed tests: $failed_tests" >&2
-		for failed_test in $failed_tests
-		do
-			if [[ $failed_test == "$test_name" ]]
-			then
-				(( found_results += 1 ))
+		for failed_test in $failed_tests; do
+			if [[ $failed_test == "$test_name" ]]; then
+				((found_results += 1))
 				printf '%s\n' "$job_log"
 			fi
 		done
 	done
-	if [[ $found_results -eq $max_results ]]
-	then
+	if [[ $found_results -eq $max_results ]]; then
 		break
 	fi
-	next_page=$(pcregrep 'x-next-page: \d+' $curl_metadata_out_file | pcregrep -o '\d+') 
-	if [[ -n "$next_page" ]] && [[ "$next_page" -le "$pages" ]]
-	then
-		page=$next_page 
+	next_page=$(pcregrep 'x-next-page: \d+' $curl_metadata_out_file | pcregrep -o '\d+')
+	if [[ -n "$next_page" ]] && [[ "$next_page" -le "$pages" ]]; then
+		page=$next_page
 	else
 		break
 	fi
diff --git a/home/scripts/site-public-ips b/home/scripts/site-public-ips
--- a/home/scripts/site-public-ips
+++ b/home/scripts/site-public-ips
@@ -1,24 +1,22 @@
 #!/usr/bin/env zsh
 
-local environment
-local site
-local usage="usage:\nsite-public-ips [environment] site-name" 
-if [ ! -v 1 ]
-then
-	echo "must specify site" >&2
-	echo "$usage" >&2
-	return 1
+set -Eeuo pipefail
+
+usage="usage:\nsite-public-ips [environment] site-name"
+if [ ! -v 1 ]; then
+  echo "must specify site" >&2
+  echo "$usage" >&2
+  exit 1
 fi
-if [ $# -eq 2 ]
-then
-	environment="$1" 
-	shift
+if [ $# -eq 2 ]; then
+  environment="$1"
+  shift
 else
-	environment=demo1 
+  environment=demo1
 fi
-local compass_hostname=$(env-compass-hostname "$environment") 
-local site_fqdn=$(env-site-fqdn "$environment") 
-site="$1" 
+compass_hostname=$(env-compass-hostname "$environment")
+site_fqdn=$(env-site-fqdn "$environment")
+site="$1"
 tf_params_objects=$(curl "https://${compass_hostname}/introspection/${site_fqdn}/vulpix/ves.io.stdlib/introspect/read/object/ves.io.vulpix.terraform_parameters.Object?response_format=1&page_start=0&page_limit=2000" \
   -H 'content-type: application/json' \
   -H 'accept: application/json' \
@@ -28,21 +26,18 @@ tf_params_objects=$(curl "https://${compass_hostname}/introspection/${site_fqdn}
   --silent \
   --fail \
   --cert-type P12 \
-  --cert ${HOME}/.ves-internal/${environment}/usercerts.p12:volterra) 
-if [[ $? -ne 0 ]]
-then
-	return $?
+  --cert ${HOME}/.ves-internal/${environment}/usercerts.p12:volterra)
+if [[ $? -ne 0 ]]; then
+  exit $?
 fi
-tf_params_id=$(printf '%s\n' "$tf_params_objects" \
-  | jq -r '.get_responses|to_entries[]|select(.value.object.system_metadata.owner_view.name == "'"$site"'")|.value.object.metadata.uid') 
-if [[ $? -ne 0 ]]
-then
-	return $?
+tf_params_id=$(printf '%s\n' "$tf_params_objects" |
+  jq -r '.get_responses|to_entries[]|select(.value.object.system_metadata.owner_view.name == "'"$site"'")|.value.object.metadata.uid')
+if [[ $? -ne 0 ]]; then
+  exit $?
 fi
-if [[ -z "$tf_params_id" ]]
-then
-	echo "could not find terraform parameters for site $site" >&2
-	return 1
+if [[ -z "$tf_params_id" ]]; then
+  echo "could not find terraform parameters for site $site" >&2
+  exit 1
 fi
 tf_status=$(curl "https://${compass_hostname}/introspection/${site_fqdn}/streak/ves.io.streak/introspect/read/status-objects" \
   -H 'content-type: application/json' \
@@ -54,22 +49,19 @@ tf_status=$(curl "https://${compass_hostname}/introspection/${site_fqdn}/streak/
   --fail \
   --silent \
   --cert-type P12 \
-  --cert ${HOME}/.ves-internal/${environment}/usercerts.p12:volterra) 
-if [[ -z "$tf_status" ]]
-then
-	echo "could not find terraform status for site $site" >&2
-	return 1
+  --cert ${HOME}/.ves-internal/${environment}/usercerts.p12:volterra)
+if [[ -z "$tf_status" ]]; then
+  echo "could not find terraform status for site $site" >&2
+  exit 1
 fi
-master_ips=$(printf '%s\n' "$tf_status" \
-  | jq -r '.config_status_map|to_entries[].value.items[].status_object_bytes.apply_status.tf_output' | grep master_public_ip_address | pcregrep -o '([\d\.]+)$') 
-if [[ -z "$master_ips" ]]
-then
-	master_ips=$(printf '%s\n' "$tf_status" | grep -A3 master_public_ip_address | pcregrep -o '\d+\.\d+\.\d+\.\d+' | pcregrep -v '^(10\.|192.168\.|172\.16\.)') 
+master_ips=$(printf '%s\n' "$tf_status" |
+  jq -r '.config_status_map|to_entries[].value.items[].status_object_bytes.apply_status.tf_output' | grep master_public_ip_address | pcregrep -o '([\d\.]+)$')
+if [[ -z "$master_ips" ]]; then
+  master_ips=$(printf '%s\n' "$tf_status" | grep -A3 master_public_ip_address | pcregrep -o '\d+\.\d+\.\d+\.\d+' | pcregrep -v '^(10\.|192.168\.|172\.16\.)')
 fi
-if [[ -z "$master_ips" ]]
-then
-	echo "could not find public IPs for site $site, terraform apply status:" >&2
-	printf '%s\n' "$tf_status" >&2
-	return 1
+if [[ -z "$master_ips" ]]; then
+  echo "could not find public IPs for site $site, terraform apply status:" >&2
+  printf '%s\n' "$tf_status" >&2
+  exit 1
 fi
 printf '%s\n' "$master_ips"
diff --git a/home/scripts/toggle-audio-input-mute b/home/scripts/toggle-audio-input-mute
--- a/home/scripts/toggle-audio-input-mute
+++ b/home/scripts/toggle-audio-input-mute
@@ -1,34 +1,32 @@
 #!/usr/bin/env zsh
 
+set -Eeuo pipefail
+
 mkdir -p ~/.local/share
-local default_input_volume=87 
-local prev_audio_input_volume_file=~/.local/share/input-volume 
+default_input_volume=87
+prev_audio_input_volume_file=~/.local/share/input-volume
 current_input_volume=$(osascript \
   -e 'tell application "System Events"' \
   -e 'get volume settings' \
-  -e 'end tell' \
-  | sd ',' '\n' \
-  | grep 'input volume:' \
-  | cut -d':' -f2) 
-if [[ -z "$current_input_volume" ]]
-then
-	echo "error: could not determine current input volume" >&2
-	return 1
+  -e 'end tell' |
+  sd ',' '\n' |
+  grep 'input volume:' |
+  cut -d':' -f2)
+if [[ -z "$current_input_volume" ]]; then
+  echo "error: could not determine current input volume" >&2
+  exit 1
 fi
-if echo "$current_input_volume" | pcregrep '\D'
-then
-	echo "error: current input volume is unexpected: $current_input_volume" >&2
-	return 1
+if echo "$current_input_volume" | pcregrep '\D'; then
+  echo "error: current input volume is unexpected: $current_input_volume" >&2
+  exit 1
 fi
-if [[ $current_input_volume -eq 0 ]]
-then
-	if [[ -f $prev_audio_input_volume_file ]]
-	then
-		set-input-volume-percent $(cat $prev_audio_input_volume_file)
-	else
-		set-input-volume-percent $default_input_volume
-	fi
+if [[ $current_input_volume -eq 0 ]]; then
+  if [[ -f $prev_audio_input_volume_file ]]; then
+    set-input-volume-percent $(cat $prev_audio_input_volume_file)
+  else
+    set-input-volume-percent $default_input_volume
+  fi
 else
-	echo -e $current_input_volume > $prev_audio_input_volume_file
-	set-input-volume-percent 0
+  echo -e $current_input_volume >$prev_audio_input_volume_file
+  set-input-volume-percent 0
 fi
